{% set name = "wrfcube" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mheikenfeld/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 82cd3b6c8ab7864184f4dc4e83e2acbbfbc3795d93297ca437b1c67ebf6709cc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - iris
    - xarray
    - cf_units

test:
  imports:
    - wrfcube
  source_files:
    - wrfcube/tests/test_dummy.py
  requires:
    - pytest
  commands:
    - pytest wrfcube/tests
about:
  home: http://github.com/mheikenfeld/wrfcube
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Load data from WRF output files (NetCDF) to iris cubes

  description: Load data from WRF output files (NetCDF) to iris cubes
  doc_url: http://wrfcube.readthedocs.io/
  dev_url: https://github.com/mheikenfeld/wrfcube

extra:
  recipe-maintainers:
    - mheikenfeld
